### ISSUE TITLE
Graphical Desktop Environment, How?

### ISSUE THREAD

**Issue by gotwig** [linuxdeepin/deepin-wsl#2]
So all I get is a command prompt but what about wayland or X?

are all apps installed? I dont understand how to make use of this.

**Comment by justforlxz** [comment]
Like other wsl distributions, you need to make additional settings. This is not for running dde on windows. It just provides a running environment that allows us to perform some operations on windows.

https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2
